spring:
  application:
    name: account-service
  
  data:
    mongodb:
      database: account_service_db
      
  cloud:
    stream:
      bindings:
        banking-notifications-out-0:
          destination: banking-notifications
          content-type: application/json
        audit-events-out-0:
          destination: audit-events
          content-type: application/json
        fraud-alerts-out-0:
          destination: fraud-alerts
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true

server:
  port: 8082

business:
  rules:
    savings:
      monthly-movement-limit: 5
      maintenance-fee: 0
    checking:
      monthly-movement-limit: 20
      maintenance-fee: 10.00
    fixed-term:
      monthly-movement-limit: 1
      allowed-movement-day: 15

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:eureka-password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    com.bank.accountservice: DEBUG
