spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.bank: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh