spring:
  application:
    name: credit-service
  
  data:
    mongodb:
      database: credit_service_db
      
  cloud:
    stream:
      bindings:
        banking-notifications-out-0:
          destination: banking-notifications
          content-type: application/json
        audit-events-out-0:
          destination: audit-events
          content-type: application/json
        fraud-alerts-out-0:
          destination: fraud-alerts
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true

server:
  port: 8083

business:
  rules:
    credit-limits:
      personal-loan: 10000.00
      business-loan: 50000.00
      personal-credit-card: 5000.00
      business-credit-card: 20000.00
    
    interest-rates:
      personal-loan: 0.15
      business-loan: 0.12
      personal-credit-card: 0.25
      business-credit-card: 0.22

logging:
  level:
    root: INFO
    com.bank.creditservice: DEBUG
