spring:
  application:
    name: customer-service
  
  data:
    mongodb:
      database: customers

server:
  port: 8081

business:
  rules:
    unique-document: true
    validate-email: true
    validate-phone: true
    max-customers-per-day: 100

logging:
  level:
    root: INFO
    com.bank.customerservice: DEBUG
